language: node_js
node_js:
  - '12'
install:
  - npm install
  - google-chrome-stable --version
  - unset PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
  - yarn --frozen-lockfile
  - npm install -g @lhci/cli
  - npm install -g firebase-tools
before_script:
  - export CHROME_PATH="$(which google-chrome-stable)"
  - google-chrome-stable --version
script:
  - npm run lint
  - npm run build
  - lhci autorun
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
