os: linux
dist: focal
language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '14'
git:
  depth: 1
  branches:
    only:
      - main
install:
  - npm install
  - npm ci
script:
  - npm run lint
  - npm run build
  - lhci autorun
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
