language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '14'
git:
  depth: 3
  branches:
    only:
      - main
install:
  - npm install
  - npm ci
  - npm install -g firebase-tools
  - npm install -g @lhci/cli@0.5.x
script:
  - npm run lint
  - npm run build
  - lhci autorun
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
