language: node_js
node_js:
  - '12'
addons:
  apt:
    packages:
      - libgconf-2-4
install:
  - npm install
  - npm ci
  - npm install -g @lhci/cli
  - npm install -g firebase-tools
script:
  - npm run lint
  - npm run build
  - npm install cypress --save-dev
  - $(npm bin)/cypress run --record
  - lhci autorun
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
