language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
install:
  - npm install
  - npm ci
  - npm install -g @lhci/cli
  - npm install -g firebase-tools
script:
  - npm run lint
  - npm run dll
  - npm run build
  - lhci autorun
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
