language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
  branches:
    only:
      - main
install:
  - npm install
  - npm install -g firebase-tools
  - npm install -g @lhci/cli@0.5.x
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint
      - run: npm run build
      - run: lhci autorun
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
