name: Lighthouse CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - name: Check repo
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install && npm install -g @lhci/cli@0.6.x && npm install -g firebase-tools
      - name: Build app
        run: npm run build
      - name: Lighthouse check
        run: lhci autorun
      - name: Firebase deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
      

